INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (1,'سُورَةُ ٱلْفَاتِحَةِ','Al-Faatiha','The Opening',7,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (2,'سُورَةُ البَقَرَةِ','Al-Baqara','The Cow',286,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (3,'سُورَةُ آلِ عِمۡرَانَ','Aal-i-Imraan','The Family of Imraan',200,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (4,'سُورَةُ النِّسَاءِ','An-Nisaa','The Women',176,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (5,'سُورَةُ المَائـِدَةِ','Al-Maaida','The Table',120,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (6,'سُورَةُ الأَنۡعَامِ','Al-An''aam','The Cattle',165,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (7,'سُورَةُ الأَعۡرَافِ','Al-A''raaf','The Heights',206,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (8,'سُورَةُ الأَنفَالِ','Al-Anfaal','The Spoils of War',75,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (9,'سُورَةُ التَّوۡبَةِ','At-Tawba','The Repentance',129,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (10,'سُورَةُ يُونُسَ','Yunus','Jonas',109,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (11,'سُورَةُ هُودٍ','Hud','Hud',123,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (12,'سُورَةُ يُوسُفَ','Yusuf','Joseph',111,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (13,'سُورَةُ الرَّعۡدِ','Ar-Ra''d','The Thunder',43,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (14,'سُورَةُ إِبۡرَاهِيمَ','Ibrahim','Abraham',52,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (15,'سُورَةُ الحِجۡرِ','Al-Hijr','The Rock',99,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (16,'سُورَةُ النَّحۡلِ','An-Nahl','The Bee',128,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (17,'سُورَةُ الإِسۡرَاءِ','Al-Israa','The Night Journey',111,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (18,'سُورَةُ الكَهۡفِ','Al-Kahf','The Cave',110,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (19,'سُورَةُ مَرۡيَمَ','Maryam','Mary',98,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (20,'سُورَةُ طه','Taa-Haa','Taa-Haa',135,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (21,'سُورَةُ الأَنبِيَاءِ','Al-Anbiyaa','The Prophets',112,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (22,'سُورَةُ الحَجِّ','Al-Hajj','The Pilgrimage',78,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (23,'سُورَةُ المُؤۡمِنُونَ','Al-Muminoon','The Believers',118,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (24,'سُورَةُ النُّورِ','An-Noor','The Light',64,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (25,'سُورَةُ الفُرۡقَانِ','Al-Furqaan','The Criterion',77,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (26,'سُورَةُ الشُّعَرَاءِ','Ash-Shu''araa','The Poets',227,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (27,'سُورَةُ النَّمۡلِ','An-Naml','The Ant',93,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (28,'سُورَةُ القَصَصِ','Al-Qasas','The Stories',88,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (29,'سُورَةُ العَنكَبُوتِ','Al-Ankaboot','The Spider',69,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (30,'سُورَةُ الرُّومِ','Ar-Room','The Romans',60,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (31,'سُورَةُ لُقۡمَانَ','Luqman','Luqman',34,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (32,'سُورَةُ السَّجۡدَةِ','As-Sajda','The Prostration',30,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (33,'سُورَةُ الأَحۡزَابِ','Al-Ahzaab','The Clans',73,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (34,'سُورَةُ سَبَإٍ','Saba','Sheba',54,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (35,'سُورَةُ فَاطِرٍ','Faatir','The Originator',45,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (36,'سُورَةُ يسٓ','Yaseen','Yaseen',83,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (37,'سُورَةُ الصَّافَّاتِ','As-Saaffaat','Those drawn up in Ranks',182,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (38,'سُورَةُ صٓ','Saad','The letter Saad',88,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (39,'سُورَةُ الزُّمَرِ','Az-Zumar','The Groups',75,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (40,'سُورَةُ غَافِرٍ','Ghafir','The Forgiver',85,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (41,'سُورَةُ فُصِّلَتۡ','Fussilat','Explained in detail',54,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (42,'سُورَةُ الشُّورَىٰ','Ash-Shura','Consultation',53,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (43,'سُورَةُ الزُّخۡرُفِ','Az-Zukhruf','Ornaments of gold',89,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (44,'سُورَةُ الدُّخَانِ','Ad-Dukhaan','The Smoke',59,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (45,'سُورَةُ الجَاثِيَةِ','Al-Jaathiya','Crouching',37,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (46,'سُورَةُ الأَحۡقَافِ','Al-Ahqaf','The Dunes',35,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (47,'سُورَةُ مُحَمَّدٍ','Muhammad','Muhammad',38,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (48,'سُورَةُ الفَتۡحِ','Al-Fath','The Victory',29,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (49,'سُورَةُ الحُجُرَاتِ','Al-Hujuraat','The Inner Apartments',18,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (50,'سُورَةُ قٓ','Qaaf','The letter Qaaf',45,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (51,'سُورَةُ الذَّارِيَاتِ','Adh-Dhaariyat','The Winnowing Winds',60,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (52,'سُورَةُ الطُّورِ','At-Tur','The Mount',49,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (53,'سُورَةُ النَّجۡمِ','An-Najm','The Star',62,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (54,'سُورَةُ القَمَرِ','Al-Qamar','The Moon',55,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (55,'سُورَةُ الرَّحۡمَٰن','Ar-Rahmaan','The Beneficent',78,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (56,'سُورَةُ الوَاقِعَةِ','Al-Waaqia','The Inevitable',96,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (57,'سُورَةُ الحَدِيدِ','Al-Hadid','The Iron',29,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (58,'سُورَةُ المُجَادلَةِ','Al-Mujaadila','The Pleading Woman',22,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (59,'سُورَةُ الحَشۡرِ','Al-Hashr','The Exile',24,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (60,'سُورَةُ المُمۡتَحنَةِ','Al-Mumtahana','She that is to be examined',13,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (61,'سُورَةُ الصَّفِّ','As-Saff','The Ranks',14,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (62,'سُورَةُ الجُمُعَةِ','Al-Jumu''a','Friday',11,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (63,'سُورَةُ المُنَافِقُونَ','Al-Munaafiqoon','The Hypocrites',11,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (64,'سُورَةُ التَّغَابُنِ','At-Taghaabun','Mutual Disillusion',18,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (65,'سُورَةُ الطَّلَاقِ','At-Talaaq','Divorce',12,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (66,'سُورَةُ التَّحۡرِيمِ','At-Tahrim','The Prohibition',12,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (67,'سُورَةُ المُلۡكِ','Al-Mulk','The Sovereignty',30,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (68,'سُورَةُ القَلَمِ','Al-Qalam','The Pen',52,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (69,'سُورَةُ الحَاقَّةِ','Al-Haaqqa','The Reality',52,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (70,'سُورَةُ المَعَارِجِ','Al-Ma''aarij','The Ascending Stairways',44,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (71,'سُورَةُ نُوحٍ','Nooh','Noah',28,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (72,'سُورَةُ الجِنِّ','Al-Jinn','The Jinn',28,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (73,'سُورَةُ المُزَّمِّلِ','Al-Muzzammil','The Enshrouded One',20,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (74,'سُورَةُ المُدَّثِّرِ','Al-Muddaththir','The Cloaked One',56,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (75,'سُورَةُ القِيَامَةِ','Al-Qiyaama','The Resurrection',40,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (76,'سُورَةُ الإِنسَانِ','Al-Insaan','Man',31,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (77,'سُورَةُ المُرۡسَلَاتِ','Al-Mursalaat','The Emissaries',50,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (78,'سُورَةُ النَّبَإِ','An-Naba','The Announcement',40,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (79,'سُورَةُ النَّازِعَاتِ','An-Naazi''aat','Those who drag forth',46,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (80,'سُورَةُ عَبَسَ','Abasa','He frowned',42,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (81,'سُورَةُ التَّكۡوِيرِ','At-Takwir','The Overthrowing',29,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (82,'سُورَةُ الانفِطَارِ','Al-Infitaar','The Cleaving',19,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (83,'سُورَةُ المُطَفِّفِينَ','Al-Mutaffifin','Defrauding',36,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (84,'سُورَةُ الانشِقَاقِ','Al-Inshiqaaq','The Splitting Open',25,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (85,'سُورَةُ البُرُوجِ','Al-Burooj','The Constellations',22,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (86,'سُورَةُ الطَّارِقِ','At-Taariq','The Morning Star',17,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (87,'سُورَةُ الأَعۡلَىٰ','Al-A''laa','The Most High',19,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (88,'سُورَةُ الغَاشِيَةِ','Al-Ghaashiya','The Overwhelming',26,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (89,'سُورَةُ الفَجۡرِ','Al-Fajr','The Dawn',30,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (90,'سُورَةُ البَلَدِ','Al-Balad','The City',20,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (91,'سُورَةُ الشَّمۡسِ','Ash-Shams','The Sun',15,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (92,'سُورَةُ اللَّيۡلِ','Al-Lail','The Night',21,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (93,'سُورَةُ الضُّحَىٰ','Ad-Dhuhaa','The Morning Hours',11,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (94,'سُورَةُ الشَّرۡحِ','Ash-Sharh','The Consolation',8,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (95,'سُورَةُ التِّينِ','At-Tin','The Fig',8,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (96,'سُورَةُ العَلَقِ','Al-Alaq','The Clot',19,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (97,'سُورَةُ القَدۡرِ','Al-Qadr','The Power, Fate',5,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (98,'سُورَةُ البَيِّنَةِ','Al-Bayyina','The Evidence',8,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (99,'سُورَةُ الزَّلۡزَلَةِ','Az-Zalzala','The Earthquake',8,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (100,'سُورَةُ العَادِيَاتِ','Al-Aadiyaat','The Chargers',11,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (101,'سُورَةُ القَارِعَةِ','Al-Qaari''a','The Calamity',11,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (102,'سُورَةُ التَّكَاثُرِ','At-Takaathur','Competition',8,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (103,'سُورَةُ العَصۡرِ','Al-Asr','The Declining Day, Epoch',3,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (104,'سُورَةُ الهُمَزَةِ','Al-Humaza','The Traducer',9,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (105,'سُورَةُ الفِيلِ','Al-Fil','The Elephant',5,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (106,'سُورَةُ قُرَيۡشٍ','Quraish','Quraysh',4,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (107,'سُورَةُ المَاعُونِ','Al-Maa''un','Almsgiving',7,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (108,'سُورَةُ الكَوۡثَرِ','Al-Kawthar','Abundance',3,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (109,'سُورَةُ الكَافِرُونَ','Al-Kaafiroon','The Disbelievers',6,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (110,'سُورَةُ النَّصۡرِ','An-Nasr','Divine Support',3,'Medinan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (111,'سُورَةُ المَسَدِ','Al-Masad','The Palm Fibre',5,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (112,'سُورَةُ الإِخۡلَاصِ','Al-Ikhlaas','Sincerity',4,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (113,'سُورَةُ الفَلَقِ','Al-Falaq','The Dawn',5,'Meccan');
INSERT INTO surah(number,name,english_name,english_name_translation,number_of_ayahs,revelation_type) VALUES (114,'سُورَةُ النَّاسِ','An-Naas','Mankind',6,'Meccan');

INSERT INTO quran_page(juz, page) VALUES (1, 1);
INSERT INTO quran_page(juz, page) VALUES (1, 2);
INSERT INTO quran_page(juz, page) VALUES (1, 3);
INSERT INTO quran_page(juz, page) VALUES (1, 4);
INSERT INTO quran_page(juz, page) VALUES (1, 5);
INSERT INTO quran_page(juz, page) VALUES (1, 6);
INSERT INTO quran_page(juz, page) VALUES (1, 7);
INSERT INTO quran_page(juz, page) VALUES (1, 8);
INSERT INTO quran_page(juz, page) VALUES (1, 9);
INSERT INTO quran_page(juz, page) VALUES (1, 10);
INSERT INTO quran_page(juz, page) VALUES (1, 11);
INSERT INTO quran_page(juz, page) VALUES (1, 12);
INSERT INTO quran_page(juz, page) VALUES (1, 13);
INSERT INTO quran_page(juz, page) VALUES (1, 14);
INSERT INTO quran_page(juz, page) VALUES (1, 15);
INSERT INTO quran_page(juz, page) VALUES (1, 16);
INSERT INTO quran_page(juz, page) VALUES (1, 17);
INSERT INTO quran_page(juz, page) VALUES (1, 18);
INSERT INTO quran_page(juz, page) VALUES (1, 19);
INSERT INTO quran_page(juz, page) VALUES (1, 20);
INSERT INTO quran_page(juz, page) VALUES (1, 21);
INSERT INTO quran_page(juz, page) VALUES (2, 1);
INSERT INTO quran_page(juz, page) VALUES (2, 2);
INSERT INTO quran_page(juz, page) VALUES (2, 3);
INSERT INTO quran_page(juz, page) VALUES (2, 4);
INSERT INTO quran_page(juz, page) VALUES (2, 5);
INSERT INTO quran_page(juz, page) VALUES (2, 6);
INSERT INTO quran_page(juz, page) VALUES (2, 7);
INSERT INTO quran_page(juz, page) VALUES (2, 8);
INSERT INTO quran_page(juz, page) VALUES (2, 9);
INSERT INTO quran_page(juz, page) VALUES (2, 10);
INSERT INTO quran_page(juz, page) VALUES (2, 11);
INSERT INTO quran_page(juz, page) VALUES (2, 12);
INSERT INTO quran_page(juz, page) VALUES (2, 13);
INSERT INTO quran_page(juz, page) VALUES (2, 14);
INSERT INTO quran_page(juz, page) VALUES (2, 15);
INSERT INTO quran_page(juz, page) VALUES (2, 16);
INSERT INTO quran_page(juz, page) VALUES (2, 17);
INSERT INTO quran_page(juz, page) VALUES (2, 18);
INSERT INTO quran_page(juz, page) VALUES (2, 19);
INSERT INTO quran_page(juz, page) VALUES (2, 20);

INSERT INTO quran_page(juz, page) VALUES (3, 1);
INSERT INTO quran_page(juz, page) VALUES (3, 2);
INSERT INTO quran_page(juz, page) VALUES (3, 3);
INSERT INTO quran_page(juz, page) VALUES (3, 4);
INSERT INTO quran_page(juz, page) VALUES (3, 5);
INSERT INTO quran_page(juz, page) VALUES (3, 6);
INSERT INTO quran_page(juz, page) VALUES (3, 7);
INSERT INTO quran_page(juz, page) VALUES (3, 8);
INSERT INTO quran_page(juz, page) VALUES (3, 9);
INSERT INTO quran_page(juz, page) VALUES (3, 10);
INSERT INTO quran_page(juz, page) VALUES (3, 11);
INSERT INTO quran_page(juz, page) VALUES (3, 12);
INSERT INTO quran_page(juz, page) VALUES (3, 13);
INSERT INTO quran_page(juz, page) VALUES (3, 14);
INSERT INTO quran_page(juz, page) VALUES (3, 15);
INSERT INTO quran_page(juz, page) VALUES (3, 16);
INSERT INTO quran_page(juz, page) VALUES (3, 17);
INSERT INTO quran_page(juz, page) VALUES (3, 18);
INSERT INTO quran_page(juz, page) VALUES (3, 19);
INSERT INTO quran_page(juz, page) VALUES (3, 20);

INSERT INTO quran_page(juz, page) VALUES (4, 1);
INSERT INTO quran_page(juz, page) VALUES (4, 2);
INSERT INTO quran_page(juz, page) VALUES (4, 3);
INSERT INTO quran_page(juz, page) VALUES (4, 4);
INSERT INTO quran_page(juz, page) VALUES (4, 5);
INSERT INTO quran_page(juz, page) VALUES (4, 6);
INSERT INTO quran_page(juz, page) VALUES (4, 7);
INSERT INTO quran_page(juz, page) VALUES (4, 8);
INSERT INTO quran_page(juz, page) VALUES (4, 9);
INSERT INTO quran_page(juz, page) VALUES (4, 10);
INSERT INTO quran_page(juz, page) VALUES (4, 11);
INSERT INTO quran_page(juz, page) VALUES (4, 12);
INSERT INTO quran_page(juz, page) VALUES (4, 13);
INSERT INTO quran_page(juz, page) VALUES (4, 14);
INSERT INTO quran_page(juz, page) VALUES (4, 15);
INSERT INTO quran_page(juz, page) VALUES (4, 16);
INSERT INTO quran_page(juz, page) VALUES (4, 17);
INSERT INTO quran_page(juz, page) VALUES (4, 18);
INSERT INTO quran_page(juz, page) VALUES (4, 19);
INSERT INTO quran_page(juz, page) VALUES (4, 20);

INSERT INTO quran_page(juz, page) VALUES (5, 1);
INSERT INTO quran_page(juz, page) VALUES (5, 2);
INSERT INTO quran_page(juz, page) VALUES (5, 3);
INSERT INTO quran_page(juz, page) VALUES (5, 4);
INSERT INTO quran_page(juz, page) VALUES (5, 5);
INSERT INTO quran_page(juz, page) VALUES (5, 6);
INSERT INTO quran_page(juz, page) VALUES (5, 7);
INSERT INTO quran_page(juz, page) VALUES (5, 8);
INSERT INTO quran_page(juz, page) VALUES (5, 9);
INSERT INTO quran_page(juz, page) VALUES (5, 10);
INSERT INTO quran_page(juz, page) VALUES (5, 11);
INSERT INTO quran_page(juz, page) VALUES (5, 12);
INSERT INTO quran_page(juz, page) VALUES (5, 13);
INSERT INTO quran_page(juz, page) VALUES (5, 14);
INSERT INTO quran_page(juz, page) VALUES (5, 15);
INSERT INTO quran_page(juz, page) VALUES (5, 16);
INSERT INTO quran_page(juz, page) VALUES (5, 17);
INSERT INTO quran_page(juz, page) VALUES (5, 18);
INSERT INTO quran_page(juz, page) VALUES (5, 19);
INSERT INTO quran_page(juz, page) VALUES (5, 20);

INSERT INTO quran_page(juz, page) VALUES (6, 1);
INSERT INTO quran_page(juz, page) VALUES (6, 2);
INSERT INTO quran_page(juz, page) VALUES (6, 3);
INSERT INTO quran_page(juz, page) VALUES (6, 4);
INSERT INTO quran_page(juz, page) VALUES (6, 5);
INSERT INTO quran_page(juz, page) VALUES (6, 6);
INSERT INTO quran_page(juz, page) VALUES (6, 7);
INSERT INTO quran_page(juz, page) VALUES (6, 8);
INSERT INTO quran_page(juz, page) VALUES (6, 9);
INSERT INTO quran_page(juz, page) VALUES (6, 10);
INSERT INTO quran_page(juz, page) VALUES (6, 11);
INSERT INTO quran_page(juz, page) VALUES (6, 12);
INSERT INTO quran_page(juz, page) VALUES (6, 13);
INSERT INTO quran_page(juz, page) VALUES (6, 14);
INSERT INTO quran_page(juz, page) VALUES (6, 15);
INSERT INTO quran_page(juz, page) VALUES (6, 16);
INSERT INTO quran_page(juz, page) VALUES (6, 17);
INSERT INTO quran_page(juz, page) VALUES (6, 18);
INSERT INTO quran_page(juz, page) VALUES (6, 19);
INSERT INTO quran_page(juz, page) VALUES (6, 20);

INSERT INTO quran_page(juz, page) VALUES (7, 1);
INSERT INTO quran_page(juz, page) VALUES (7, 2);
INSERT INTO quran_page(juz, page) VALUES (7, 3);
INSERT INTO quran_page(juz, page) VALUES (7, 4);
INSERT INTO quran_page(juz, page) VALUES (7, 5);
INSERT INTO quran_page(juz, page) VALUES (7, 6);
INSERT INTO quran_page(juz, page) VALUES (7, 7);
INSERT INTO quran_page(juz, page) VALUES (7, 8);
INSERT INTO quran_page(juz, page) VALUES (7, 9);
INSERT INTO quran_page(juz, page) VALUES (7, 10);
INSERT INTO quran_page(juz, page) VALUES (7, 11);
INSERT INTO quran_page(juz, page) VALUES (7, 12);
INSERT INTO quran_page(juz, page) VALUES (7, 13);
INSERT INTO quran_page(juz, page) VALUES (7, 14);
INSERT INTO quran_page(juz, page) VALUES (7, 15);
INSERT INTO quran_page(juz, page) VALUES (7, 16);
INSERT INTO quran_page(juz, page) VALUES (7, 17);
INSERT INTO quran_page(juz, page) VALUES (7, 18);
INSERT INTO quran_page(juz, page) VALUES (7, 19);
INSERT INTO quran_page(juz, page) VALUES (7, 20);

INSERT INTO quran_page(juz, page) VALUES (8, 1);
INSERT INTO quran_page(juz, page) VALUES (8, 2);
INSERT INTO quran_page(juz, page) VALUES (8, 3);
INSERT INTO quran_page(juz, page) VALUES (8, 4);
INSERT INTO quran_page(juz, page) VALUES (8, 5);
INSERT INTO quran_page(juz, page) VALUES (8, 6);
INSERT INTO quran_page(juz, page) VALUES (8, 7);
INSERT INTO quran_page(juz, page) VALUES (8, 8);
INSERT INTO quran_page(juz, page) VALUES (8, 9);
INSERT INTO quran_page(juz, page) VALUES (8, 10);
INSERT INTO quran_page(juz, page) VALUES (8, 11);
INSERT INTO quran_page(juz, page) VALUES (8, 12);
INSERT INTO quran_page(juz, page) VALUES (8, 13);
INSERT INTO quran_page(juz, page) VALUES (8, 14);
INSERT INTO quran_page(juz, page) VALUES (8, 15);
INSERT INTO quran_page(juz, page) VALUES (8, 16);
INSERT INTO quran_page(juz, page) VALUES (8, 17);
INSERT INTO quran_page(juz, page) VALUES (8, 18);
INSERT INTO quran_page(juz, page) VALUES (8, 19);
INSERT INTO quran_page(juz, page) VALUES (8, 20);

INSERT INTO quran_page(juz, page) VALUES (9, 1);
INSERT INTO quran_page(juz, page) VALUES (9, 2);
INSERT INTO quran_page(juz, page) VALUES (9, 3);
INSERT INTO quran_page(juz, page) VALUES (9, 4);
INSERT INTO quran_page(juz, page) VALUES (9, 5);
INSERT INTO quran_page(juz, page) VALUES (9, 6);
INSERT INTO quran_page(juz, page) VALUES (9, 7);
INSERT INTO quran_page(juz, page) VALUES (9, 8);
INSERT INTO quran_page(juz, page) VALUES (9, 9);
INSERT INTO quran_page(juz, page) VALUES (9, 10);
INSERT INTO quran_page(juz, page) VALUES (9, 11);
INSERT INTO quran_page(juz, page) VALUES (9, 12);
INSERT INTO quran_page(juz, page) VALUES (9, 13);
INSERT INTO quran_page(juz, page) VALUES (9, 14);
INSERT INTO quran_page(juz, page) VALUES (9, 15);
INSERT INTO quran_page(juz, page) VALUES (9, 16);
INSERT INTO quran_page(juz, page) VALUES (9, 17);
INSERT INTO quran_page(juz, page) VALUES (9, 18);
INSERT INTO quran_page(juz, page) VALUES (9, 19);
INSERT INTO quran_page(juz, page) VALUES (9, 20);

INSERT INTO quran_page(juz, page) VALUES (10, 1);
INSERT INTO quran_page(juz, page) VALUES (10, 2);
INSERT INTO quran_page(juz, page) VALUES (10, 3);
INSERT INTO quran_page(juz, page) VALUES (10, 4);
INSERT INTO quran_page(juz, page) VALUES (10, 5);
INSERT INTO quran_page(juz, page) VALUES (10, 6);
INSERT INTO quran_page(juz, page) VALUES (10, 7);
INSERT INTO quran_page(juz, page) VALUES (10, 8);
INSERT INTO quran_page(juz, page) VALUES (10, 9);
INSERT INTO quran_page(juz, page) VALUES (10, 10);
INSERT INTO quran_page(juz, page) VALUES (10, 11);
INSERT INTO quran_page(juz, page) VALUES (10, 12);
INSERT INTO quran_page(juz, page) VALUES (10, 13);
INSERT INTO quran_page(juz, page) VALUES (10, 14);
INSERT INTO quran_page(juz, page) VALUES (10, 15);
INSERT INTO quran_page(juz, page) VALUES (10, 16);
INSERT INTO quran_page(juz, page) VALUES (10, 17);
INSERT INTO quran_page(juz, page) VALUES (10, 18);
INSERT INTO quran_page(juz, page) VALUES (10, 19);
INSERT INTO quran_page(juz, page) VALUES (10, 20);

INSERT INTO quran_page(juz, page) VALUES (11, 1);
INSERT INTO quran_page(juz, page) VALUES (11, 2);
INSERT INTO quran_page(juz, page) VALUES (11, 3);
INSERT INTO quran_page(juz, page) VALUES (11, 4);
INSERT INTO quran_page(juz, page) VALUES (11, 5);
INSERT INTO quran_page(juz, page) VALUES (11, 6);
INSERT INTO quran_page(juz, page) VALUES (11, 7);
INSERT INTO quran_page(juz, page) VALUES (11, 8);
INSERT INTO quran_page(juz, page) VALUES (11, 9);
INSERT INTO quran_page(juz, page) VALUES (11, 10);
INSERT INTO quran_page(juz, page) VALUES (11, 11);
INSERT INTO quran_page(juz, page) VALUES (11, 12);
INSERT INTO quran_page(juz, page) VALUES (11, 13);
INSERT INTO quran_page(juz, page) VALUES (11, 14);
INSERT INTO quran_page(juz, page) VALUES (11, 15);
INSERT INTO quran_page(juz, page) VALUES (11, 16);
INSERT INTO quran_page(juz, page) VALUES (11, 17);
INSERT INTO quran_page(juz, page) VALUES (11, 18);
INSERT INTO quran_page(juz, page) VALUES (11, 19);
INSERT INTO quran_page(juz, page) VALUES (11, 20);

INSERT INTO quran_page(juz, page) VALUES (12, 1);
INSERT INTO quran_page(juz, page) VALUES (12, 2);
INSERT INTO quran_page(juz, page) VALUES (12, 3);
INSERT INTO quran_page(juz, page) VALUES (12, 4);
INSERT INTO quran_page(juz, page) VALUES (12, 5);
INSERT INTO quran_page(juz, page) VALUES (12, 6);
INSERT INTO quran_page(juz, page) VALUES (12, 7);
INSERT INTO quran_page(juz, page) VALUES (12, 8);
INSERT INTO quran_page(juz, page) VALUES (12, 9);
INSERT INTO quran_page(juz, page) VALUES (12, 10);
INSERT INTO quran_page(juz, page) VALUES (12, 11);
INSERT INTO quran_page(juz, page) VALUES (12, 12);
INSERT INTO quran_page(juz, page) VALUES (12, 13);
INSERT INTO quran_page(juz, page) VALUES (12, 14);
INSERT INTO quran_page(juz, page) VALUES (12, 15);
INSERT INTO quran_page(juz, page) VALUES (12, 16);
INSERT INTO quran_page(juz, page) VALUES (12, 17);
INSERT INTO quran_page(juz, page) VALUES (12, 18);
INSERT INTO quran_page(juz, page) VALUES (12, 19);
INSERT INTO quran_page(juz, page) VALUES (12, 20);

INSERT INTO quran_page(juz, page) VALUES (13, 1);
INSERT INTO quran_page(juz, page) VALUES (13, 2);
INSERT INTO quran_page(juz, page) VALUES (13, 3);
INSERT INTO quran_page(juz, page) VALUES (13, 4);
INSERT INTO quran_page(juz, page) VALUES (13, 5);
INSERT INTO quran_page(juz, page) VALUES (13, 6);
INSERT INTO quran_page(juz, page) VALUES (13, 7);
INSERT INTO quran_page(juz, page) VALUES (13, 8);
INSERT INTO quran_page(juz, page) VALUES (13, 9);
INSERT INTO quran_page(juz, page) VALUES (13, 10);
INSERT INTO quran_page(juz, page) VALUES (13, 11);
INSERT INTO quran_page(juz, page) VALUES (13, 12);
INSERT INTO quran_page(juz, page) VALUES (13, 13);
INSERT INTO quran_page(juz, page) VALUES (13, 14);
INSERT INTO quran_page(juz, page) VALUES (13, 15);
INSERT INTO quran_page(juz, page) VALUES (13, 16);
INSERT INTO quran_page(juz, page) VALUES (13, 17);
INSERT INTO quran_page(juz, page) VALUES (13, 18);
INSERT INTO quran_page(juz, page) VALUES (13, 19);
INSERT INTO quran_page(juz, page) VALUES (13, 20);

INSERT INTO quran_page(juz, page) VALUES (14, 1);
INSERT INTO quran_page(juz, page) VALUES (14, 2);
INSERT INTO quran_page(juz, page) VALUES (14, 3);
INSERT INTO quran_page(juz, page) VALUES (14, 4);
INSERT INTO quran_page(juz, page) VALUES (14, 5);
INSERT INTO quran_page(juz, page) VALUES (14, 6);
INSERT INTO quran_page(juz, page) VALUES (14, 7);
INSERT INTO quran_page(juz, page) VALUES (14, 8);
INSERT INTO quran_page(juz, page) VALUES (14, 9);
INSERT INTO quran_page(juz, page) VALUES (14, 10);
INSERT INTO quran_page(juz, page) VALUES (14, 11);
INSERT INTO quran_page(juz, page) VALUES (14, 12);
INSERT INTO quran_page(juz, page) VALUES (14, 13);
INSERT INTO quran_page(juz, page) VALUES (14, 14);
INSERT INTO quran_page(juz, page) VALUES (14, 15);
INSERT INTO quran_page(juz, page) VALUES (14, 16);
INSERT INTO quran_page(juz, page) VALUES (14, 17);
INSERT INTO quran_page(juz, page) VALUES (14, 18);
INSERT INTO quran_page(juz, page) VALUES (14, 19);
INSERT INTO quran_page(juz, page) VALUES (14, 20);

INSERT INTO quran_page(juz, page) VALUES (15, 1);
INSERT INTO quran_page(juz, page) VALUES (15, 2);
INSERT INTO quran_page(juz, page) VALUES (15, 3);
INSERT INTO quran_page(juz, page) VALUES (15, 4);
INSERT INTO quran_page(juz, page) VALUES (15, 5);
INSERT INTO quran_page(juz, page) VALUES (15, 6);
INSERT INTO quran_page(juz, page) VALUES (15, 7);
INSERT INTO quran_page(juz, page) VALUES (15, 8);
INSERT INTO quran_page(juz, page) VALUES (15, 9);
INSERT INTO quran_page(juz, page) VALUES (15, 10);
INSERT INTO quran_page(juz, page) VALUES (15, 11);
INSERT INTO quran_page(juz, page) VALUES (15, 12);
INSERT INTO quran_page(juz, page) VALUES (15, 13);
INSERT INTO quran_page(juz, page) VALUES (15, 14);
INSERT INTO quran_page(juz, page) VALUES (15, 15);
INSERT INTO quran_page(juz, page) VALUES (15, 16);
INSERT INTO quran_page(juz, page) VALUES (15, 17);
INSERT INTO quran_page(juz, page) VALUES (15, 18);
INSERT INTO quran_page(juz, page) VALUES (15, 19);
INSERT INTO quran_page(juz, page) VALUES (15, 20);

INSERT INTO quran_page(juz, page) VALUES (16, 1);
INSERT INTO quran_page(juz, page) VALUES (16, 2);
INSERT INTO quran_page(juz, page) VALUES (16, 3);
INSERT INTO quran_page(juz, page) VALUES (16, 4);
INSERT INTO quran_page(juz, page) VALUES (16, 5);
INSERT INTO quran_page(juz, page) VALUES (16, 6);
INSERT INTO quran_page(juz, page) VALUES (16, 7);
INSERT INTO quran_page(juz, page) VALUES (16, 8);
INSERT INTO quran_page(juz, page) VALUES (16, 9);
INSERT INTO quran_page(juz, page) VALUES (16, 10);
INSERT INTO quran_page(juz, page) VALUES (16, 11);
INSERT INTO quran_page(juz, page) VALUES (16, 12);
INSERT INTO quran_page(juz, page) VALUES (16, 13);
INSERT INTO quran_page(juz, page) VALUES (16, 14);
INSERT INTO quran_page(juz, page) VALUES (16, 15);
INSERT INTO quran_page(juz, page) VALUES (16, 16);
INSERT INTO quran_page(juz, page) VALUES (16, 17);
INSERT INTO quran_page(juz, page) VALUES (16, 18);
INSERT INTO quran_page(juz, page) VALUES (16, 19);
INSERT INTO quran_page(juz, page) VALUES (16, 20);

INSERT INTO quran_page(juz, page) VALUES (17, 1);
INSERT INTO quran_page(juz, page) VALUES (17, 2);
INSERT INTO quran_page(juz, page) VALUES (17, 3);
INSERT INTO quran_page(juz, page) VALUES (17, 4);
INSERT INTO quran_page(juz, page) VALUES (17, 5);
INSERT INTO quran_page(juz, page) VALUES (17, 6);
INSERT INTO quran_page(juz, page) VALUES (17, 7);
INSERT INTO quran_page(juz, page) VALUES (17, 8);
INSERT INTO quran_page(juz, page) VALUES (17, 9);
INSERT INTO quran_page(juz, page) VALUES (17, 10);
INSERT INTO quran_page(juz, page) VALUES (17, 11);
INSERT INTO quran_page(juz, page) VALUES (17, 12);
INSERT INTO quran_page(juz, page) VALUES (17, 13);
INSERT INTO quran_page(juz, page) VALUES (17, 14);
INSERT INTO quran_page(juz, page) VALUES (17, 15);
INSERT INTO quran_page(juz, page) VALUES (17, 16);
INSERT INTO quran_page(juz, page) VALUES (17, 17);
INSERT INTO quran_page(juz, page) VALUES (17, 18);
INSERT INTO quran_page(juz, page) VALUES (17, 19);
INSERT INTO quran_page(juz, page) VALUES (17, 20);

INSERT INTO quran_page(juz, page) VALUES (18, 1);
INSERT INTO quran_page(juz, page) VALUES (18, 2);
INSERT INTO quran_page(juz, page) VALUES (18, 3);
INSERT INTO quran_page(juz, page) VALUES (18, 4);
INSERT INTO quran_page(juz, page) VALUES (18, 5);
INSERT INTO quran_page(juz, page) VALUES (18, 6);
INSERT INTO quran_page(juz, page) VALUES (18, 7);
INSERT INTO quran_page(juz, page) VALUES (18, 8);
INSERT INTO quran_page(juz, page) VALUES (18, 9);
INSERT INTO quran_page(juz, page) VALUES (18, 10);
INSERT INTO quran_page(juz, page) VALUES (18, 11);
INSERT INTO quran_page(juz, page) VALUES (18, 12);
INSERT INTO quran_page(juz, page) VALUES (18, 13);
INSERT INTO quran_page(juz, page) VALUES (18, 14);
INSERT INTO quran_page(juz, page) VALUES (18, 15);
INSERT INTO quran_page(juz, page) VALUES (18, 16);
INSERT INTO quran_page(juz, page) VALUES (18, 17);
INSERT INTO quran_page(juz, page) VALUES (18, 18);
INSERT INTO quran_page(juz, page) VALUES (18, 19);
INSERT INTO quran_page(juz, page) VALUES (18, 20);

INSERT INTO quran_page(juz, page) VALUES (19, 1);
INSERT INTO quran_page(juz, page) VALUES (19, 2);
INSERT INTO quran_page(juz, page) VALUES (19, 3);
INSERT INTO quran_page(juz, page) VALUES (19, 4);
INSERT INTO quran_page(juz, page) VALUES (19, 5);
INSERT INTO quran_page(juz, page) VALUES (19, 6);
INSERT INTO quran_page(juz, page) VALUES (19, 7);
INSERT INTO quran_page(juz, page) VALUES (19, 8);
INSERT INTO quran_page(juz, page) VALUES (19, 9);
INSERT INTO quran_page(juz, page) VALUES (19, 10);
INSERT INTO quran_page(juz, page) VALUES (19, 11);
INSERT INTO quran_page(juz, page) VALUES (19, 12);
INSERT INTO quran_page(juz, page) VALUES (19, 13);
INSERT INTO quran_page(juz, page) VALUES (19, 14);
INSERT INTO quran_page(juz, page) VALUES (19, 15);
INSERT INTO quran_page(juz, page) VALUES (19, 16);
INSERT INTO quran_page(juz, page) VALUES (19, 17);
INSERT INTO quran_page(juz, page) VALUES (19, 18);
INSERT INTO quran_page(juz, page) VALUES (19, 19);
INSERT INTO quran_page(juz, page) VALUES (19, 20);

INSERT INTO quran_page(juz, page) VALUES (20, 1);
INSERT INTO quran_page(juz, page) VALUES (20, 2);
INSERT INTO quran_page(juz, page) VALUES (20, 3);
INSERT INTO quran_page(juz, page) VALUES (20, 4);
INSERT INTO quran_page(juz, page) VALUES (20, 5);
INSERT INTO quran_page(juz, page) VALUES (20, 6);
INSERT INTO quran_page(juz, page) VALUES (20, 7);
INSERT INTO quran_page(juz, page) VALUES (20, 8);
INSERT INTO quran_page(juz, page) VALUES (20, 9);
INSERT INTO quran_page(juz, page) VALUES (20, 10);
INSERT INTO quran_page(juz, page) VALUES (20, 11);
INSERT INTO quran_page(juz, page) VALUES (20, 12);
INSERT INTO quran_page(juz, page) VALUES (20, 13);
INSERT INTO quran_page(juz, page) VALUES (20, 14);
INSERT INTO quran_page(juz, page) VALUES (20, 15);
INSERT INTO quran_page(juz, page) VALUES (20, 16);
INSERT INTO quran_page(juz, page) VALUES (20, 17);
INSERT INTO quran_page(juz, page) VALUES (20, 18);
INSERT INTO quran_page(juz, page) VALUES (20, 19);
INSERT INTO quran_page(juz, page) VALUES (20, 20);

INSERT INTO quran_page(juz, page) VALUES (21, 1);
INSERT INTO quran_page(juz, page) VALUES (21, 2);
INSERT INTO quran_page(juz, page) VALUES (21, 3);
INSERT INTO quran_page(juz, page) VALUES (21, 4);
INSERT INTO quran_page(juz, page) VALUES (21, 5);
INSERT INTO quran_page(juz, page) VALUES (21, 6);
INSERT INTO quran_page(juz, page) VALUES (21, 7);
INSERT INTO quran_page(juz, page) VALUES (21, 8);
INSERT INTO quran_page(juz, page) VALUES (21, 9);
INSERT INTO quran_page(juz, page) VALUES (21, 10);
INSERT INTO quran_page(juz, page) VALUES (21, 11);
INSERT INTO quran_page(juz, page) VALUES (21, 12);
INSERT INTO quran_page(juz, page) VALUES (21, 13);
INSERT INTO quran_page(juz, page) VALUES (21, 14);
INSERT INTO quran_page(juz, page) VALUES (21, 15);
INSERT INTO quran_page(juz, page) VALUES (21, 16);
INSERT INTO quran_page(juz, page) VALUES (21, 17);
INSERT INTO quran_page(juz, page) VALUES (21, 18);
INSERT INTO quran_page(juz, page) VALUES (21, 19);
INSERT INTO quran_page(juz, page) VALUES (21, 20);

INSERT INTO quran_page(juz, page) VALUES (22, 1);
INSERT INTO quran_page(juz, page) VALUES (22, 2);
INSERT INTO quran_page(juz, page) VALUES (22, 3);
INSERT INTO quran_page(juz, page) VALUES (22, 4);
INSERT INTO quran_page(juz, page) VALUES (22, 5);
INSERT INTO quran_page(juz, page) VALUES (22, 6);
INSERT INTO quran_page(juz, page) VALUES (22, 7);
INSERT INTO quran_page(juz, page) VALUES (22, 8);
INSERT INTO quran_page(juz, page) VALUES (22, 9);
INSERT INTO quran_page(juz, page) VALUES (22, 10);
INSERT INTO quran_page(juz, page) VALUES (22, 11);
INSERT INTO quran_page(juz, page) VALUES (22, 12);
INSERT INTO quran_page(juz, page) VALUES (22, 13);
INSERT INTO quran_page(juz, page) VALUES (22, 14);
INSERT INTO quran_page(juz, page) VALUES (22, 15);
INSERT INTO quran_page(juz, page) VALUES (22, 16);
INSERT INTO quran_page(juz, page) VALUES (22, 17);
INSERT INTO quran_page(juz, page) VALUES (22, 18);
INSERT INTO quran_page(juz, page) VALUES (22, 19);
INSERT INTO quran_page(juz, page) VALUES (22, 20);

INSERT INTO quran_page(juz, page) VALUES (23, 1);
INSERT INTO quran_page(juz, page) VALUES (23, 2);
INSERT INTO quran_page(juz, page) VALUES (23, 3);
INSERT INTO quran_page(juz, page) VALUES (23, 4);
INSERT INTO quran_page(juz, page) VALUES (23, 5);
INSERT INTO quran_page(juz, page) VALUES (23, 6);
INSERT INTO quran_page(juz, page) VALUES (23, 7);
INSERT INTO quran_page(juz, page) VALUES (23, 8);
INSERT INTO quran_page(juz, page) VALUES (23, 9);
INSERT INTO quran_page(juz, page) VALUES (23, 10);
INSERT INTO quran_page(juz, page) VALUES (23, 11);
INSERT INTO quran_page(juz, page) VALUES (23, 12);
INSERT INTO quran_page(juz, page) VALUES (23, 13);
INSERT INTO quran_page(juz, page) VALUES (23, 14);
INSERT INTO quran_page(juz, page) VALUES (23, 15);
INSERT INTO quran_page(juz, page) VALUES (23, 16);
INSERT INTO quran_page(juz, page) VALUES (23, 17);
INSERT INTO quran_page(juz, page) VALUES (23, 18);
INSERT INTO quran_page(juz, page) VALUES (23, 19);
INSERT INTO quran_page(juz, page) VALUES (23, 20);

INSERT INTO quran_page(juz, page) VALUES (24, 1);
INSERT INTO quran_page(juz, page) VALUES (24, 2);
INSERT INTO quran_page(juz, page) VALUES (24, 3);
INSERT INTO quran_page(juz, page) VALUES (24, 4);
INSERT INTO quran_page(juz, page) VALUES (24, 5);
INSERT INTO quran_page(juz, page) VALUES (24, 6);
INSERT INTO quran_page(juz, page) VALUES (24, 7);
INSERT INTO quran_page(juz, page) VALUES (24, 8);
INSERT INTO quran_page(juz, page) VALUES (24, 9);
INSERT INTO quran_page(juz, page) VALUES (24, 10);
INSERT INTO quran_page(juz, page) VALUES (24, 11);
INSERT INTO quran_page(juz, page) VALUES (24, 12);
INSERT INTO quran_page(juz, page) VALUES (24, 13);
INSERT INTO quran_page(juz, page) VALUES (24, 14);
INSERT INTO quran_page(juz, page) VALUES (24, 15);
INSERT INTO quran_page(juz, page) VALUES (24, 16);
INSERT INTO quran_page(juz, page) VALUES (24, 17);
INSERT INTO quran_page(juz, page) VALUES (24, 18);
INSERT INTO quran_page(juz, page) VALUES (24, 19);
INSERT INTO quran_page(juz, page) VALUES (24, 20);

INSERT INTO quran_page(juz, page) VALUES (25, 1);
INSERT INTO quran_page(juz, page) VALUES (25, 2);
INSERT INTO quran_page(juz, page) VALUES (25, 3);
INSERT INTO quran_page(juz, page) VALUES (25, 4);
INSERT INTO quran_page(juz, page) VALUES (25, 5);
INSERT INTO quran_page(juz, page) VALUES (25, 6);
INSERT INTO quran_page(juz, page) VALUES (25, 7);
INSERT INTO quran_page(juz, page) VALUES (25, 8);
INSERT INTO quran_page(juz, page) VALUES (25, 9);
INSERT INTO quran_page(juz, page) VALUES (25, 10);
INSERT INTO quran_page(juz, page) VALUES (25, 11);
INSERT INTO quran_page(juz, page) VALUES (25, 12);
INSERT INTO quran_page(juz, page) VALUES (25, 13);
INSERT INTO quran_page(juz, page) VALUES (25, 14);
INSERT INTO quran_page(juz, page) VALUES (25, 15);
INSERT INTO quran_page(juz, page) VALUES (25, 16);
INSERT INTO quran_page(juz, page) VALUES (25, 17);
INSERT INTO quran_page(juz, page) VALUES (25, 18);
INSERT INTO quran_page(juz, page) VALUES (25, 19);
INSERT INTO quran_page(juz, page) VALUES (25, 20);

INSERT INTO quran_page(juz, page) VALUES (26, 1);
INSERT INTO quran_page(juz, page) VALUES (26, 2);
INSERT INTO quran_page(juz, page) VALUES (26, 3);
INSERT INTO quran_page(juz, page) VALUES (26, 4);
INSERT INTO quran_page(juz, page) VALUES (26, 5);
INSERT INTO quran_page(juz, page) VALUES (26, 6);
INSERT INTO quran_page(juz, page) VALUES (26, 7);
INSERT INTO quran_page(juz, page) VALUES (26, 8);
INSERT INTO quran_page(juz, page) VALUES (26, 9);
INSERT INTO quran_page(juz, page) VALUES (26, 10);
INSERT INTO quran_page(juz, page) VALUES (26, 11);
INSERT INTO quran_page(juz, page) VALUES (26, 12);
INSERT INTO quran_page(juz, page) VALUES (26, 13);
INSERT INTO quran_page(juz, page) VALUES (26, 14);
INSERT INTO quran_page(juz, page) VALUES (26, 15);
INSERT INTO quran_page(juz, page) VALUES (26, 16);
INSERT INTO quran_page(juz, page) VALUES (26, 17);
INSERT INTO quran_page(juz, page) VALUES (26, 18);
INSERT INTO quran_page(juz, page) VALUES (26, 19);
INSERT INTO quran_page(juz, page) VALUES (26, 20);

INSERT INTO quran_page(juz, page) VALUES (27, 1);
INSERT INTO quran_page(juz, page) VALUES (27, 2);
INSERT INTO quran_page(juz, page) VALUES (27, 3);
INSERT INTO quran_page(juz, page) VALUES (27, 4);
INSERT INTO quran_page(juz, page) VALUES (27, 5);
INSERT INTO quran_page(juz, page) VALUES (27, 6);
INSERT INTO quran_page(juz, page) VALUES (27, 7);
INSERT INTO quran_page(juz, page) VALUES (27, 8);
INSERT INTO quran_page(juz, page) VALUES (27, 9);
INSERT INTO quran_page(juz, page) VALUES (27, 10);
INSERT INTO quran_page(juz, page) VALUES (27, 11);
INSERT INTO quran_page(juz, page) VALUES (27, 12);
INSERT INTO quran_page(juz, page) VALUES (27, 13);
INSERT INTO quran_page(juz, page) VALUES (27, 14);
INSERT INTO quran_page(juz, page) VALUES (27, 15);
INSERT INTO quran_page(juz, page) VALUES (27, 16);
INSERT INTO quran_page(juz, page) VALUES (27, 17);
INSERT INTO quran_page(juz, page) VALUES (27, 18);
INSERT INTO quran_page(juz, page) VALUES (27, 19);
INSERT INTO quran_page(juz, page) VALUES (27, 20);

INSERT INTO quran_page(juz, page) VALUES (28, 1);
INSERT INTO quran_page(juz, page) VALUES (28, 2);
INSERT INTO quran_page(juz, page) VALUES (28, 3);
INSERT INTO quran_page(juz, page) VALUES (28, 4);
INSERT INTO quran_page(juz, page) VALUES (28, 5);
INSERT INTO quran_page(juz, page) VALUES (28, 6);
INSERT INTO quran_page(juz, page) VALUES (28, 7);
INSERT INTO quran_page(juz, page) VALUES (28, 8);
INSERT INTO quran_page(juz, page) VALUES (28, 9);
INSERT INTO quran_page(juz, page) VALUES (28, 10);
INSERT INTO quran_page(juz, page) VALUES (28, 11);
INSERT INTO quran_page(juz, page) VALUES (28, 12);
INSERT INTO quran_page(juz, page) VALUES (28, 13);
INSERT INTO quran_page(juz, page) VALUES (28, 14);
INSERT INTO quran_page(juz, page) VALUES (28, 15);
INSERT INTO quran_page(juz, page) VALUES (28, 16);
INSERT INTO quran_page(juz, page) VALUES (28, 17);
INSERT INTO quran_page(juz, page) VALUES (28, 18);
INSERT INTO quran_page(juz, page) VALUES (28, 19);
INSERT INTO quran_page(juz, page) VALUES (28, 20);

INSERT INTO quran_page(juz, page) VALUES (29, 1);
INSERT INTO quran_page(juz, page) VALUES (29, 2);
INSERT INTO quran_page(juz, page) VALUES (29, 3);
INSERT INTO quran_page(juz, page) VALUES (29, 4);
INSERT INTO quran_page(juz, page) VALUES (29, 5);
INSERT INTO quran_page(juz, page) VALUES (29, 6);
INSERT INTO quran_page(juz, page) VALUES (29, 7);
INSERT INTO quran_page(juz, page) VALUES (29, 8);
INSERT INTO quran_page(juz, page) VALUES (29, 9);
INSERT INTO quran_page(juz, page) VALUES (29, 10);
INSERT INTO quran_page(juz, page) VALUES (29, 11);
INSERT INTO quran_page(juz, page) VALUES (29, 12);
INSERT INTO quran_page(juz, page) VALUES (29, 13);
INSERT INTO quran_page(juz, page) VALUES (29, 14);
INSERT INTO quran_page(juz, page) VALUES (29, 15);
INSERT INTO quran_page(juz, page) VALUES (29, 16);
INSERT INTO quran_page(juz, page) VALUES (29, 17);
INSERT INTO quran_page(juz, page) VALUES (29, 18);
INSERT INTO quran_page(juz, page) VALUES (29, 19);
INSERT INTO quran_page(juz, page) VALUES (29, 20);

INSERT INTO quran_page(juz, page) VALUES (30, 1);
INSERT INTO quran_page(juz, page) VALUES (30, 2);
INSERT INTO quran_page(juz, page) VALUES (30, 3);
INSERT INTO quran_page(juz, page) VALUES (30, 4);
INSERT INTO quran_page(juz, page) VALUES (30, 5);
INSERT INTO quran_page(juz, page) VALUES (30, 6);
INSERT INTO quran_page(juz, page) VALUES (30, 7);
INSERT INTO quran_page(juz, page) VALUES (30, 8);
INSERT INTO quran_page(juz, page) VALUES (30, 9);
INSERT INTO quran_page(juz, page) VALUES (30, 10);
INSERT INTO quran_page(juz, page) VALUES (30, 11);
INSERT INTO quran_page(juz, page) VALUES (30, 12);
INSERT INTO quran_page(juz, page) VALUES (30, 13);
INSERT INTO quran_page(juz, page) VALUES (30, 14);
INSERT INTO quran_page(juz, page) VALUES (30, 15);
INSERT INTO quran_page(juz, page) VALUES (30, 16);
INSERT INTO quran_page(juz, page) VALUES (30, 17);
INSERT INTO quran_page(juz, page) VALUES (30, 18);
INSERT INTO quran_page(juz, page) VALUES (30, 19);
INSERT INTO quran_page(juz, page) VALUES (30, 20);
INSERT INTO quran_page(juz, page) VALUES (30, 21);
INSERT INTO quran_page(juz, page) VALUES (30, 22);
INSERT INTO quran_page(juz, page) VALUES (30, 23);
